# Generated by Django 3.2.4 on 2021-06-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='m', upload_to='images'),
            preserve_default=False,
        ),
    ]
